// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqJc6SXSt3YqEe8odV_lotINOLYzEWYK4',
    appId: '1:81111986828:web:f41db86e14de59448181a9',
    messagingSenderId: '81111986828',
    projectId: 'trnk-ice',
    authDomain: 'trnk-ice.firebaseapp.com',
    storageBucket: 'trnk-ice.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeWewWsEj6PKwi4NHje5qsD0jfc70jLeg',
    appId: '1:81111986828:android:dff8e1bbe1500f408181a9',
    messagingSenderId: '81111986828',
    projectId: 'trnk-ice',
    storageBucket: 'trnk-ice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQrfZ9PcpXwzr0wUp_INs2YT7Sp0VDkLE',
    appId: '1:81111986828:ios:c127f7dc6a4ebe078181a9',
    messagingSenderId: '81111986828',
    projectId: 'trnk-ice',
    storageBucket: 'trnk-ice.appspot.com',
    iosBundleId: 'com.asa.trnkIce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQrfZ9PcpXwzr0wUp_INs2YT7Sp0VDkLE',
    appId: '1:81111986828:ios:5964417c839f1b158181a9',
    messagingSenderId: '81111986828',
    projectId: 'trnk-ice',
    storageBucket: 'trnk-ice.appspot.com',
    iosBundleId: 'com.asa.trnkIce.RunnerTests',
  );
}
